### ISSUE TITLE
`readlink -f` not possible on Mac

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/dataClay#1]
not major, but it would help testing if fixed

**Comment by alexbarcelo** [comment]
It doesn't seem an inmediate fix, if support for corner cases is desired...

https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by alexbarcelo** [comment]
Fixed in 517a88668ccefa3c258335eb5fff527ede2a6242
