### ISSUE TITLE
String quotation in filters are not correctly processed

### ISSUE THREAD

**Issue by alexbarcelo** [mF2C/dataClay#14]
Closing #13 in favour of this more specific issue.

~~Seems that when there are double quotes in a filter query, those are not correctly processed and dataClay does not behave correctly.~~

~~Now that this is detected, we are working on it. ATM, it seems that is safe to use by avoiding filtering by strings with double quotes. Either avoid double quotes in values, or avoid filtering by them. Next version will have solved that.~~

Working on it. Completely messed up the interpretation.

Note that we have been using the following to test the filtering mechanism:

    (require '[com.sixsq.slipstream.ssclj.filter.parser :as parser])
    (print (parser/parse-cimi-filter "<stuff here>"))

We assume that this print matches what the DataClayWrapper will be receiving.

Originally reported by @cjdcordeiro

**Comment by cjdcordeiro** [comment]
if attribute is single quoted, like this (guarantee):

```python
{
    "constraint" : "var1 < 100 and var2 > 100",
    "updated" : "2018-06-07T13:39:23.606Z",
    "created" : "2018-06-07T13:39:23.606Z",
    "guarantee" : "'asdasd'",
    "id" : "sla-violation/686caece-0cd8-4235-bdc2-d9d267f8a3c7",
    "values" : {
      "var2" : 100,
      "var1" : 101
    },
    "datetime" : "2018-04-11T10:39:51.527008088Z",
    "acl" : {
      "owner" : {
        "principal" : "ADMIN",
        "type" : "ROLE"
      }
    },
    "operations" : [ {
      "rel" : "edit",
      "href" : "sla-violation/686caece-0cd8-4235-bdc2-d9d267f8a3c7"
    }, {
      "rel" : "delete",
      "href" : "sla-violation/686caece-0cd8-4235-bdc2-d9d267f8a3c7"
    } ],
    "resourceURI" : "http://schemas.dmtf.org/cimi/2/SlaViolation",
    "agreement_id" : {
      "href" : "agreement/4e529393-f659-44d6-9c8b-b0589132599b"
    }
```

and the filter is `curl -XGET -ksS -H 'content-type: application/json' -H 'slipstream-authn-info: internal ADMIN' 'https://localhost/api/sla-violation?$filter=guarantee="asdasd"'`

still, not resources will be returned

**Comment by alexbarcelo** [comment]
No sorry, we want to know what is the AST when the curl URL is:

`https://localhost/api/sla-violation?$filter=guarantee='asdasd'`

Just to double check parameters, quotes and escapes on the AST-structure-clojure-that-thing-string-passed-to-java and its query digest are working as expected.

Quotes should not be required in the fields, so we are not really interested on that.

**Comment by alexbarcelo** [comment]
I am asking instead of testing because our tests through 

```
(require '[com.sixsq.slipstream.ssclj.filter.parser :as parser])
(print (parser/parse-cimi-filter "<stuff here>"))
```

seems to have divergent behaviour of your `Expression` log line, and I still don't understand what happens with the quotes and when do they appear and when do they disappear, as your `Expression` logging line shows things like the operator `"="` but I have seen some prints with `=`  and still don't know what is each thing and its impact.

**Comment by cjdcordeiro** [comment]
well that shouldn't matter. It depends on the language/REST library you are using...cimi dictates that the attribute value, if it is a string, should be passed as so, but here it goes:

```bash
+ curl -XGET -ksS -H 'content-type: application/json' -H 'slipstream-authn-info: internal ADMIN' 'https://localhost/api/sla-violation?$filter=guarantee='\''TestGuarantee2'\'''
{
  "acl" : {
    "owner" : {
      "principal" : "ADMIN",
      "type" : "ROLE"
    },
    "rules" : [ {
      "principal" : "USER",
      "type" : "ROLE",
      "right" : "MODIFY"
    } ]
  },
  "resourceURI" : "http://schemas.dmtf.org/cimi/2/SlaViolationCollection",
  "id" : "sla-violation",
  "operations" : [ {
    "rel" : "add",
    "href" : "sla-violation"
  } ],
  "slaViolations" : [ ]
}
```


the same happens

**Comment by alexbarcelo** [comment]
@cjdcordeiro 
> It depends on the language/REST library you are using

You are referring to the REST library that @loomis used to do the dataclay-proxy "bridge"? We don't have any issue with the strings in the REST (and no control over it whatsover). I am concerned that this issue is related to the _string representation in the string representation of the AST_(sic). The code that we prepared for the CIMI integration expects an AST and we used the following:

    (require '[com.sixsq.slipstream.ssclj.filter.parser :as parser])
    (print (parser/parse-cimi-filter "<stuff here>"))

which we assumed that it was what you were using. That returns something along:

    [:Filter [:AndExpr [:Comp (...) [:Attribute guarantee] [:EqOp =] [:DoubleQuoteString "TestGuarantee"] (...)

However, our tests assumed that the representation of the strings in the string representation of the AST(sic) was like:

    (...) [:DoubleQuoteString "TestGuarantee"] (...)

And I don't know if it is the logging library, the storage, JSON witchery, a real difference on the string, or what; but now it seems like there is an extra double quote there:

    (...) [:DoubleQuoteString "\"TestGuarantee\""] (...)

And this seems a mismatch, maybe the problem.

To address this we need to understand the quote usage **exactly**, because unitary tests done in our end worked, maybe because there is a underlying misunderstandment on the format?

The `curl` command is not directly useful check our filter function because we are assuming a certain transformation to AST (done by clojure / SixSq / Cal / CIMI implementation / ?). But you haven't confirmed that this is correct:

    (require '[com.sixsq.slipstream.ssclj.filter.parser :as parser])
    (print (parser/parse-cimi-filter "<stuff here>"))

**Comment by loomis** [comment]
The AST contains the **exact** value given to the parser, including the quotes.  For a :DoubleQuoteString (:SingleQuoteString) you have to strip the leading and trailing double (single) quotes from the value when doing comparisons.

**Comment by alexbarcelo** [comment]
Still:

    (...) [:DoubleQuoteString "TestGuarantee"] (...)

or

    (...) [:DoubleQuoteString "\"TestGuarantee\""] (...)

and also:

    [:EqOp =]

or:

    [:EqOp "="]

What is Java receiving as a parameter?

**Comment by loomis** [comment]
The string containing the AST is generated with the `str` function, which does not format its output in the same way as `print`.

```
(require '[com.sixsq.slipstream.db.filter.parser :as parser])
(def q "alpha != 'one' and beta = \"two\" and gamma > 100 and delta = false")
(str (parser/parse-cimi-filter q))
"[:Filter [:AndExpr [:Comp [:Attribute \"alpha\"] [:EqOp \"!=\"] [:SingleQuoteString \"'one'\"]] [:AndExpr [:Comp [:Attribute \"beta\"] [:EqOp \"=\"] [:DoubleQuoteString \"\\\"two\\\"\"]] [:AndExpr [:Comp [:Attribute \"gamma\"] [:RelOp \">\"] [:IntValue \"100\"]] [:AndExpr [:Comp [:Attribute \"delta\"] [:EqOp \"=\"] [:BoolValue \"false\"]]]]]]]"
```

Without the multiple levels of escaping the query is:

```
alpha != 'one' and beta = "two" and gamma > 100 and delta = false
```

which produces the AST:

```
[:Filter [:AndExpr [:Comp [:Attribute "alpha"] [:EqOp "!="] [:SingleQuoteString "'one'"]] [:AndExpr [:Comp [:Attribute "beta"] [:EqOp "="] [:DoubleQuoteString "\"two\""]] [:AndExpr [:Comp [:Attribute "gamma"] [:RelOp ">"] [:IntValue "100"]] [:AndExpr [:Comp [:Attribute "delta"] [:EqOp "="] [:BoolValue "false"]]]]]]]
```

The strings have the literal quotes as part of their values.

**Comment by alexbarcelo** [comment]
Thanks for all the clarifications and the example. I think that now I understand the issue and how to address it. We will start by changing the way we tested our code, ofc.

**Comment by alexbarcelo** [comment]
We fixed our tests by using the `(str` clojure thingy, and were able to fix all the string filtering issues that were triggered by that change.

The docker image has been uploaded (the jar is inside, as in previous versions). Also, should now be compliant with the expected AST representation (thanks to 71412e4e74422e155b7d648ce62fe42dd3a83449 if everything is ok). The dcproxy image should use the updated jar and the updated DataClayWrapper class.

@cjdcordeiro, we will be waiting for your ok before closing this issue.

**Comment by cjdcordeiro** [comment]
seems to be working thanks
