### ISSUE TITLE
fix error propagation from dataclay-proxy to cimi

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/dataClay#20]

**Comment by aqueralt** [comment]
Hi Cris, can you provide more information about this issue? Is it that errors from dataClay are not propagated to the dataclay-proxy, or from the dataclay-proxy to CIMI? And which errors are they?

**Comment by cjdcordeiro** [comment]
Hi @aqueralt 
for example: 

```
Cristovaos-MacBook-Pro:_demo cristovaocordeiro$ curl -XPOST https://localhost/api/user -k -H 'content-type:application/json' -d @addRegularUser.json 
{
  "status" : 201,
  "message" : "user/testusercristests2 created",
  "resource-id" : "user/testusercristests2"
}Cristovaos-MacBook-Pro:_demo cristovaocordeiro$ 
Cristovaos-MacBook-Pro:_demo cristovaocordeiro$ 
Cristovaos-MacBook-Pro:_demo cristovaocordeiro$ curl -XPOST https://localhost/api/user -k -H 'content-type:application/json' -d @addRegularUser.json 
{
  "status" : 405,
  "message" : "invalid method (post) for /api/user",
  "resource-id" : "/api/user"
}
```

in summary, what should be a 409 (conflict, because the user already exists), returns a 405. CIMI gets this from the proxy, but I'm not sure whether the proxy gets it from someplace else or not

**Comment by aqueralt** [comment]
Hi @cjdcordeiro 
We return an exception when there is an attempt to create the same resource twice (among others). Then I guess that the Clojure part of the proxy is what transforms this exception into an error code for CIMI. Can you check whether you need some more information from our part to do this?

**Comment by cjdcordeiro** [comment]
@aqueralt I've been running some tests and basically, CIMI is getting the output back from the dcproxy just right.

The problem seems to be in between dcproxy and dataclay.

To reproduce the problem you can simply deploy dcproxy and dataclay, go inside the dcproxy container and run:
```
curl -XPOST http://localhost:6472/ -d '''[:add {:activeSince "1970-01-01T00:00:00.000Z", :lastExecute "1970-01-01T00:00:00.000Z", :deleted false, :password "E9E633097AB9CEB3E48EC3F70EE2BEBA41D05D5420EFEE5DA85F97D97005727587FDA33EF4FF2322088F4C79E8133CC9CD9F3512F4D3A303CBDB5BC585415A00", :method "self-registration", :updated "2018-10-19T14:04:00.064Z", :emailAddress "something@test.com", :username "testusercristests2", :created "2018-10-19T14:04:00.064Z", :state "NEW", :lastOnline "1970-01-01T00:00:00.000Z", :id "user/testusercristests2", :acl {:owner {:principal "ADMIN", :type "ROLE"}, :rules [{:principal "ADMIN", :type "ROLE", :right "ALL"} {:principal "testusercristests2", :type "USER", :right "MODIFY"}]}, :resourceURI "http://sixsq.com/slipstream/1/User", :isSuperUser false} {}]'''
```

run it twice!!

You'll see the first output is 201, but the second is 500 when it should be a 409.

If you find that the problem is with the dcproxy, we might be able to help you fix it if you're not too comfortable with Clojure...or maybe the best if that you recreate the proxy in your preferred language, as longs as it keeps the REST interface with the same methods

**Comment by aqueralt** [comment]
@cjdcordeiro We just tested and dataClay returns an AliasAlreadyInUseException when there is an attempt to use the same id twice. It is the dcproxy that turns exceptions into error codes. If you need some other information to process our outputs and return the correct codes, just tell us which other errors you want to handle and we will tell you how to recognise them.

**Comment by cjdcordeiro** [comment]
@aqueralt then the problem might be in the error parsing of the dcproxy. this is something you are maintaining now. If you need help understanding the code we can help but we no longer maintaining our fork of the dataclay repository - "Latest commit e498a15  on Jun 20"

**Comment by aqueralt** [comment]
@cjdcordeiro This commit you mention was about moving our files (which of course we are maintaining) to the 'dataclay-proxy' folder (CIMI-dataClay integration) to avoid having them duplicated. I don't see why this should mean that we are also maintaining your part of the code. Probably we should discuss this on a call.

**Comment by cjdcordeiro** [comment]
@aqueralt sure we can have a talk. I'm free today and tomorrow.

**Comment by aqueralt** [comment]
@cjdcordeiro can we close this ticket? With the DataClayWrapper in maven and returning more kinds of exceptions, this should be solved in the new integration CIMI-DataClay

**Comment by cjdcordeiro** [comment]
yes
Best regards,

*Cristóvão Cordeiro*
R&D Project Manager
*LinkedIn <https://www.linkedin.com/in/cristovaocordeiro/>*

*SixSq*
*8 Rue du Bois-du-Lan*
*1217 Meyrin*
*Geneva*
*Switzerland*
