### ISSUE TITLE
fix the dependency between CIMI and DataClay

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/dataClay#22]
needed by https://github.com/mF2C/cimi/issues/30

implement/adopt one of the following options:

 1. pickup the work done in the dcproxy and take it from there, solving the existing propagation issue in https://github.com/mF2C/cimi/issues/30
 2. properly package the dataclay libraries in a public repository so it can be added as a dependency from CIMI
 3. build a language agnostic API for dataclay, like REST or SOAP

**Comment by aqueralt** [comment]
Working on option 2. Currently improving the DataClayWrapper so that it provides more information about dataClay errors to the dcproxy

**Comment by aqueralt** [comment]
DataClayWrapper with error propagation included, and everything in Maven. Will be uploaded (also the new docker-composes) today-tomorrow.

**Comment by aqueralt** [comment]
@cjdcordeiro you can access it here, with instructions and javadoc: https://github.com/bsc-ssrg/dataclay-maven-mf2c-wrapper
Just let us know if everything is ok.

**Comment by cjdcordeiro** [comment]
this is already being implemented (internally, at https://github.com/slipstream/SlipStreamServer/issues/1737)

A 1st update is:
 - the integration of the DC dependency with CIMI generated several conflicts. However, at a first glance, these seem relatively easy to fix since the discrepancies are mostly due to different software patches. 

The timeline for delivering this is mid January

**Comment by cjdcordeiro** [comment]
now being addressed at https://github.com/mF2C/cimi/issues/42
