### ISSUE TITLE
Update Service resource in Dataclay

### ISSUE THREAD

**Issue by fcarp10** [mF2C/dataClay#26]

**Comment by aqueralt** [comment]
Hi Fran, this depends on a CIMI resource spec that is not yet available, right?

**Comment by fcarp10** [comment]
No, not yet. I just created it to have it in mind for the next sprint.

**Comment by aqueralt** [comment]
@fcarp10 Hi Fran, the dataClay dockers including the new service definition are already available. Please tell us if you find some problem with the Hello World, thanks!

**Comment by fcarp10** [comment]
Hi Anna, are the docker images pushed into docker cloud? I cannot find them.

**Comment by alexbarcelo** [comment]
They seem to be at docker *hub* properly tagged: https://hub.docker.com/r/bscdataclay/logicmodule/tags

Could you confirm if there is any issue with the mF2C `docker-compose.yml` orchestration and the dataClay images?
