### ISSUE TITLE
Check whether some CIMI resource is missing in dC

### ISSUE THREAD

**Issue by aqueralt** [mF2C/dataClay#27]
Verify that all resource types inserted by CIMI are included in the dataClay model.
Currently we have:
- cloud-entry-point
- email
- user
- credential
- session
- session-template
- callback
Any other type that we need to handle?

**Comment by cjdcordeiro** [comment]
I think this can be closed. `configuration` is missing, but for now that's a default CIMI resource we don't make use of

**Comment by aqueralt** [comment]
Ok, closing then
