### ISSUE TITLE
Define new data model for agents

### ISSUE THREAD

**Issue by aqueralt** [mF2C/dataClay#30]
According to the needs of the Discovery process, we propose a new (additional) CIMI resource called "agent" with (at least) the following information:
- own device ID
- leader ID
- leader IP
- authenticated?
- connected?

This resource is created in each device once it has been authenticated. 
Each device/agent will have a single instance of this resource (it is not shared with other agents, neither with the leader). This allows components to obtain their own device ID or their leader ID by querying CIMI with /agent, which will always return a single resource.

The rest of related CIMI resources ("device" and "device-dynamic") remain the same, except that we can remove the leaderID from "device-dynamic" because it is now in "agent". Also, if a leader queries for /device or /device-dynamic, it will still get the info for all its children, as happens now.

**Comment by rsucasas** [comment]
- own device IP

It could be useful for the lifecycle to know its own IP address

**Comment by aqueralt** [comment]
@rsucasas this field is already in the associated device resource identified by the device ID in agent

**Comment by daniwhere** [comment]
Implemented Agent in dataClay according to specification in #23 

Implemented in PR https://github.com/mF2C/mF2C/pull/139
