### ISSUE TITLE
Improve flexibility in resource updates

### ISSUE THREAD

**Issue by aqueralt** [mF2C/dataClay#32]
Re-design the mapping from CIMI resources to dataClay classes so that developers just need to update the CIMI resource spec, without depending on a new dataClay release that incorporates the changes

**Comment by daniwhere** [comment]
Finally we require developers to also update the Java class of the resource type they want to modify or add a new one. The idea is to modify the code so developers only need to add the fields, do a PR and wait for dataclay to publish a new docker image.

**Comment by daniwhere** [comment]
Developers will need just to modify  https://github.com/mF2C/dataClay/tree/master/cimi_dataclay/model/src/CIMI classes 
A class would look like:

public class Credential extends CIMIResource {
	// An attribute for each field in the CIMI resource spec, with the same name and
	// type.If it contains nested info or its a href, it is implemented as a Map<String, Object>
	// where String is the field name, and Object is the value
	// WARNING: All fields must be public or no modifier defined.
	String type; 
	String method; 
	//credential-template/method
	//Constructor
	public Credential(final Map<String, Object> objectData) {
		super(objectData);
	}
}
