### ISSUE TITLE
dc/dcproxy returning NIL for edit operations

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/dataClay#36]

**Comment by daniwhere** [comment]
Hi @cjdcordeiro currently dataclay is not returning anything for edit operations, do you expect the object with changed fields?

**Comment by cjdcordeiro** [comment]
yep that would be ideal and in accordance with the existing convention

**Comment by daniwhere** [comment]
Fixed. Added pull request https://github.com/mF2C/mF2C/pull/125 .Waiting for your review.
