### ISSUE TITLE
Fix query ACLs

### ISSUE THREAD

**Issue by dgasull** [mF2C/dataClay#47]
As specified by cris:

the issue is: if a collection ACL has a rule saying that ANON can view or modify etc., then no matter what the individual resources’ acls are, ANON will be able to see everything
example: if you register your user in CIMI…me, as ANON, I can see your password
the way it should work is that upon a query, CIMI passes you a filter, and that filter should be checked agains each and every single resource in a collection

**Comment by cjdcordeiro** [comment]
lgtm
